# Spec file for Product Manager CLI
# (C) Copyright 2021 Hewlett Packard Enterprise Development LP.

Name: cray-prodmgr
Version: %(./tools/changelog.py ./CHANGELOG.md)
License: HPE Proprietary
Release: %(echo ${BUILD_METADATA})
Source: %{name}-%{version}.tar.gz
Summary: Shasta Product Manager CLI
Group: System/Management
BuildRoot: %{_topdir}
Vendor: Hewlett Packard Enterprise Company
Requires: kubectl
Requires: podman
Requires: python3-PyYAML


%description
The prodmgr command is responsible for launching product install utility images.

%prep
%setup -n %{name}-%{version}

%build

%install
python3 setup.py install -O1 --root="$RPM_BUILD_ROOT" --record=INSTALLED_FILES \
                             --install-scripts=/usr/bin

# This is a hack taken from the DST-EXAMPLES / example-rpm-python repo to get
# the package directory, i.e. /usr/lib/python3.6/site-packages/sat which is not
# included in the INSTALLED_FILES list generated by setup.py.
# TODO: Replace this hack with something better, perhaps using %python_sitelib
cat INSTALLED_FILES | grep __pycache__ | xargs dirname | xargs dirname | uniq >> INSTALLED_FILES

# Our top-level `prodmgr` script is currently installed by specifying our main
# function as an entry_point. Thus is it installed by `setup.py` above and
# listed in INSTALLED_FILES. If we change how that script is generated, we will
# need to manually install it here.

%files -f INSTALLED_FILES
